project:
  type: manuscript

execute:
  freeze: auto

format:
  html:
    toc: true
    comments:
      hypothesis: true
  docx:
    toc: true
    toc-title: Зміст
    number-sections: true
    reference-docx: custom-reference-doc.docx
  pdf: 
    mainfont: Roboto
    monofont: Roboto
    fontfamily: roboto



